title: "மௌன வியாக்கியானம் | The Quiet Vyakhya"
author: "Harihara Subramanian"
description: "வேதாந்தம், கவிதை, இன்ன பிற மொழிநடைகள் குறித்த அகக் களத் தியானம். | Inward contemplations on Vedanta, poetry, and nuances of language."
url: "https://quiet-vyakhya.github.io"
baseurl: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

future: true
timezone: Asia/Kolkata
