title: "The Quiet Vyakhya | மௌன வியாக்கியானம்"
author: "Harihara Subramanian"
description: "Inward contemplations on Vedanta, poetry, and nuances of language. | வேதாந்தம், கவிதை, இன்ன பிற மொழிநடைகள் குறித்த அகக் களத் தியானம்."
url: "https://quiet-vyakhya.github.io"
baseurl: ""
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

future: true
timezone: Asia/Kolkata
